---

  - name: create local file structure for shared files
    become: yes
    file: path={{ item.path }} owner={{ item.unix_user | default(user) }} group={{ item.unix_group | default(group) }} state=directory recurse=no
    with_items: "{{ file_shares }}"

  - name: set owner and group for shared files
    become: yes
    command: find {{ item.path }} ! -user {{ item.unix_user | default(user) }} ! -group {{ item.unix_group | default(group) }} ! -name 'lost+found' -exec chown {{ item.unix_user | default(user) }}:{{ item.unix_group | default(group) }} {} \; -exec echo "{}" \;
    with_items: "{{ file_shares }}"
    register: result
    changed_when: result.stdout | length > 0

  - name: set permission of all folders in directory tree to {{folder_mode}}
    become: yes
    command: find {{ item.path }} -type d ! -perm {{folder_mode}} ! -name 'lost+found' -exec chmod {{folder_mode}} {} \; -exec echo "{}" \;
    with_items: "{{ file_shares }}"
    register: result
    changed_when: result.stdout | length > 0

  - name: set permission of all files in directory tree to {{file_mode}}
    become: yes
    command: find {{ item.path }} -type f ! -perm {{file_mode}} ! -name 'lost+found' -exec chmod {{file_mode}} {} \; -exec echo "{}" \;
    with_items: "{{ file_shares }}"
    register: result
    changed_when: result.stdout | length > 0