---

  - name: create local file structure for shared files
    become: yes
    file: path={{ item.path }} owner={{ user }} group={{ group }} state=directory recurse=yes
    with_items: "{{ file_shares }}"

  - name: set permission of all folders in directory tree to {{folder_mode}}
    become: yes
    command: find {{ item.path }} -type d ! -perm {{folder_mode}} -exec chmod {{folder_mode}} {} \; -exec echo "{}" \;
    with_items: "{{ file_shares }}"
    register: result
    changed_when: result.stdout | length > 0

  - name: set permission of all files in directory tree to {{file_mode}}
    become: yes
    command: find {{ item.path }} -type f ! -perm {{file_mode}} -exec chmod {{file_mode}} {} \; -exec echo "{}" \;
    with_items: "{{ file_shares }}"
    register: result
    changed_when: result.stdout | length > 0