---

  - name: install nfs service
    become: yes
    apt: name=nfs-kernel-server state=latest
    when: (nfs_enabled is defined) and nfs_enabled and ((public_file_shares is defined) or (public_readonly_file_shares is defined))

  - name: share public files with nfs for fast access
    become: yes
    lineinfile: dest=/etc/exports line="{{ item.path }} {{ nfs_network_mask }}(ro,async,all_squash,insecure)" regexp={{ item.path }}
    with_items: "{{ public_file_shares }}"
    when: (nfs_enabled is defined) and nfs_enabled and (public_file_shares is defined)
    notify: restart nfs

  - name: share public readonly files with nfs for fast access
    become: yes
    lineinfile: dest=/etc/exports line="{{ item.path }} {{ nfs_network_mask }}(ro,async,all_squash,insecure)" regexp={{ item.path }}
    with_items: "{{ public_readonly_file_shares }}"
    when: (nfs_enabled is defined) and nfs_enabled and (public_readonly_file_shares is defined)
    notify: restart nfs
  
  - name: uninstall nfs if not enabled
    become: yes
    apt: name=nfs-kernel-server state=absent purge=true
    when: (nfs_enabled is defined) and not nfs_enabled

  - name: remove config if nfs if not enabled
    become: yes
    file:
      path: "/etc/exports"
      state: "absent"
    when: (nfs_enabled is defined) and not nfs_enabled